### ISSUE TITLE
recover deleted but cached chat

### ISSUE THREAD

**Issue by tobieeniafe** [handlerug/TelegramSwift#4]
Hi. I know this isn't an issue per say, but I need your help.

An important conversation was cleared on my telegram by accident, but luckily, the conversation is still cached on my macbook. Is there anyway to recover or export the conversation? I know the app's files are stored in `~/Library/Group Containers/*.ru.keepcoder.Telegram` but that's as far as I got. HELP!!!

**Comment by handlerug** [comment]
@tobieeniafe Sorry, that's a wrong repository to report Telegram errors. This repository is a fork of official Telegram client. You should submit this issue to https://github.com/overtake/TelegramSwift/issues/new. You can also ask the developer about this issue in t.me/macswift group chat. Regarding your issue, what I know is that database is (or was?) unencrypted, so you can find a file which is named something like db.sqlite in your account folder (if you can run the app, you can easily find the data folder by pressing Settings cog icon 5-10 times and pressing Open logs, but I think you got the path right) and try to export your convos manually using SQLite command line tools or some sort of GUI. You can also refer to Postbox and TelegramCore code located in Telegram iOS repository (you can find a link at https://telegram.org/apps. I'm not that knowledgeable in how iOS and macOS Telegram apps store application data, though.
